### ISSUE TITLE
Steam Friends contracts

### ISSUE THREAD

**Issue by rejedai** [LennardF1989/Hitman-5-Server#1]
Firstly, thank you so much for creating this wonderful project.

Secondly, I would like to use this project to unlock achievements on steam, there is an achievement to launch a contract created by a friend, how does the game technically distinguish whether a contract was created by a friend, by steamid? Is it possible to implement it in this project?

**Comment by LennardF1989** [comment]
Thank you for the kind words! Your best bet is using the Steam Achievement Manager to unlock the achievements. The server has no capability to do it, since unlocking things is a client-side thing (most of the time).

**Comment by rejedai** [comment]
I would be more interested in making this work without SAM :D

The achievement is triggered on the client side, I know that, but he is triggered at the moment after checking whether the contract creator is a friend or not.

**Comment by LennardF1989** [comment]
See the v1.0.0 release I made :) Closing this!
