### ISSUE TITLE
Small Issue with Runtime Required

### ISSUE THREAD

**Issue by devildwarf** [LennardF1989/Hitman-5-Server#4]
Noticed a small bug if you run the "Portable" version with only the .NET 6.0 runtime it will fail to open, you get this error

`
You must install or update .NET to run this application.

App: C:\Users\test\Desktop\Portable\HM5.Server.exe
Architecture: x64
Framework: Microsoft.AspNetCore.App, version 6.0.0 (x64)
.NET location: C:\Program Files\dotnet\

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=6.0.0&arch=x64
`

You need to install "ASP.NET Core Runtime" too
THIS ONLY APPLIES TO PORTABLE, the published version works great without that runtime.
Also on a sidenote the Hook DLL requires VC_redist 2015 installed which should probably be noted (or you could recompile with MT flag).

Also great work on fixing the HTTPS bug and adding money to the appsettings.json, you are doing great work thank you.

**Comment by LennardF1989** [comment]
I think you are confusing the .NET Framework (which only goes up to v4.8) vs .NET Core (5 and beyond)? How is the .NET 6.0 runtime you mention/installed different from the one that error tells you about?

Good point about the VC redist, I'll mention that somewhere.

**Comment by devildwarf** [comment]
> 

OK when you download the .NET6 runtime you are given these options on the site, IF you install just the .NET runtime or Desktop Runtime the server still fails to run, you need to install the ASP .NET runtime, i have no idea why the hell .NET6 made 3 different parts to .NET6 but they did, see screenshot
![image](https://github.com/LennardF1989/Hitman-5-Server/assets/73285343/ddd8cc4f-4851-459a-9c47-ab94dfd359f4)
This does only apply to the portable version (the Published version runs fine without the runtimes)

**Comment by LennardF1989** [comment]
I've clarified the instructions. Thanks :) It needs the ASP.NET Core because this is a web application, Desktop applications don't have a web stack (usually). I understand why they separated it, but also why it's annoying for normal users :P

I'll see if I can recompile the hook at some point with the /MT flag.

**Comment by LennardF1989** [comment]
Fixed in v1.2.0!
