### ISSUE TITLE
Can't create and open contracts page

### ISSUE THREAD

**Issue by rejedai** [LennardF1989/Hitman-5-Server#5]
When I try to create contract or open http://localhost:40147/contracts , I get an exception. 
Linux version 1.2.2.
[debug.txt](https://github.com/LennardF1989/Hitman-5-Server/files/12102561/debug.txt)

**Comment by LennardF1989** [comment]
You didn't enable `UseCustomContracts` :) That said, I will look into conditionally disabling this Controller.
